---
hostname: "10.123.10.195"
username: "okan"
password: "Welkom@1234"
device: "juniper"
bgp:
  asn: "65001"
  neighbors:
    - "1.1.1.1"
    - "2.2.2.2"
    - "3.3.3.3"
  networks:
    - "10.0.0.0/24"
    - "172.17.1.0/24"