---
HOSTNAME: "R1"
OSPF:
  - interface: "ge-0/0/0.0"
    area: "0.0.0.0"
  - interface: "ge-0/0/1.1"
    area: "0.0.0.0"
BGP:
  ASN: "65001"
  ASN_TYPE: "private"
SNMP:
  - community: "R1-Com3"
  - community: "R1-Com4"