---
inventory:
  plugin: SimpleInventory
  options: 
    host_file: "host.yaml"
    group_file: "group.yaml"
    defaults_file: "defaults.yaml"
runner:
  plugin: threaded
  options: 
    num_workers: 10
