---
R1:
  hostname: "10.123.10.195"
  groups:
    - juniper
  data:
    bgp:
      asn: 65001
    snmp: "Juniper-R1-Community"
R2:
  hostname: "10.123.10.196"
  groups:
    - juniper
  data:
    bgp:
      asn: 5
